# Generated by Django 4.2.30 on 2026-08-08 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_alter_assign_id_alter_assigntime_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendanceclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.attendanceclass'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.class'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.dept'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'attendanceclass')},
        ),
    ]
